language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=sqlite
  - ZEROMQ_VERSION=v3.2.5

before_script:
  - git clone https://github.com/mkoppanen/php-zmq.git
  - sh -c "cd php-zmq && phpize && ./configure && make --silent && sudo make install"
  - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install

script:
  - phpunit

