homepage:
    path:     /
    defaults: { _controller: 'Tchess\Controller\GameController::indexAction' }

practice:
    path:     /practice
    defaults: { _controller: 'Tchess\Controller\GameController::practiceAction' }

register:
    path:     /register
    defaults: { _controller: 'Tchess\Controller\GameController::registerAction' }

logout:
    path:     /logout
    defaults: { _controller: 'Tchess\Controller\GameController::logoutAction' }

rooms:
    path:     /rooms/{page}
    defaults: { _controller: 'Tchess\Controller\RoomController::indexAction', page: 1 }

create_room:
    path:     /create-room
    defaults: { _controller: 'Tchess\Controller\RoomController::createAction' }

join_room:
    path:     /join-room/{room}
    defaults: { _controller: 'Tchess\Controller\GameController::joinAction' }
    requirements:
        room:  \d+

watch_game:
    path:     /room/{room}
    defaults: { _controller: 'Tchess\Controller\GameController::watchAction' }
    requirements:
        room:  \d+

leave_room:
    path:     /leave-room
    defaults: { _controller: 'Tchess\Controller\GameController::leaveAction' }

move_piece:
    path:     /move-piece
    defaults: { _controller: 'Tchess\Controller\GameController::moveAction', _format: 'json' }
    methods:  [POST]
