join_game:
    path:     /join-game
    defaults: { _controller: 'Tchess\Controller\GameController::joinAction', _format: 'json' }
    methods:  [POST]

start_game:
    path:     /start-game
    defaults: { _controller: 'Tchess\Controller\GameController::startAction', _format: 'json' }
    methods:  [POST]

stop_game:
    path:     /stop-game
    defaults: { _controller: 'Tchess\Controller\GameController::stopAction', _format: 'json' }
    methods:  [POST]

restart_game:
    path:     /restart-game
    defaults: { _controller: 'Tchess\Controller\GameController::restartAction', _format: 'json' }
    methods:  [POST]

piece_move:
    path:     /piece-move
    defaults: { _controller: 'Tchess\Controller\GameController::moveAction', _format: 'json' }
    methods:  [POST]
